
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: desafioateliware_development


test:
  <<: *default
  database: desafioateliware_test


production:
  <<: *default
  database: postgres://ec2-52-87-107-83.compute-1.amazonaws.com:5432
  username: dxzppaketcgduj
  password: 20792bbc0a72f528a1df096b81d2d4881691f7f679c68a0376eb7fcfe1468bfd